In [ ]:
# 모듈 
#함수나 변수 ,클래스 파일 정의들의 파이썬 코드가 저장된 소스파일이다.

#모듈은 포쥰모듈과 그외 모듈로 정의한다. 표준모듈은 파이썬설치시자동으로 설치되는것 그외 모듈은 외부모듈을 이야기한다.
#그외 모듈은 우리가 직접 만들어서 사용하거나 , 써드파티 모듈을 설치해 이용할수있음.
#third party module --> numpy , matplotlib 등등
#표준모듈 --> turtle , random , math 등등 

#import sys --> sys모듈의 
#print(sys.builtin_module_names) --> 표존 모듈의 이름들을 확인할수있다.

# import math 
# dir(math) --> dir 함수를 통해서 math 모듈의 관련함수 , 변수등의 리스트등을 확인할수있다. 

#help(math.fsum) --> help함수의 모듈명.함수 를 사용해서 해당 역할을 검색할수있다.

#import 구문은 콤마를 이용해서 여러개를 불러올수있다. 
#import math,sys 
#import math as m --> as구문을통해 math 함수를 m 으로 컨트롤 할수 있게 한다.

#from math import degree --> from구문을통해 math모듈에들어있는 degree 함수를 모듈이름 없이 바로 사용할수있도록한다





In [1]:
# 9-1 코딩

import math 
print(math.pi) # 원주율 pi

from math import e # 자연수 e
print(math.e)
from math import degrees,radians
print(degrees(math.pi), radians(90))
from math import floor, ceil 
# 바닥값 , 천장값 floor(실수) : 실수보다 작거나 같은 가장 큰 정수, ceil(실수) : 실수보다 크같 가장작은정수
print(floor(3.8), ceil(3.1))

from math import factorial as fact #n! 엔펙토리얼 함수 
print(fact(5))



3.141592653589793
2.718281828459045
180.0 1.5707963267948966
3 4
120


In [5]:
# 9-2 코딩
#random 함수의 suffle(리스트의값을 섞어서 출력)
#random 함수의 ranodm(0부터 1까지의 실수를 발생)
#random 함수의 sample(0,1) 0 리스트 1 갯수 의 난수를 발생

import random as rd 

for i in range(3):
    print(rd.random()) # 0에서 1보다 작은 실수 난수 생성
cards = [[1,'송학'],[2,'메조'],[3,'벚꽃'],[4,'흑싸리'],[5,'초'],[6,'모란']]
print(cards)

for _ in range(3):
    rd.shuffle(cards) # 카드를 랜덤으로 섞음
    print(cards)
    
print(rd.sample(cards,2)) # 카드에서 2개를 랜덤으로 선택 

0.5941635482647823
0.7877783965506993
0.29499051321733116
[[1, '송학'], [2, '메조'], [3, '벚꽃'], [4, '흑싸리'], [5, '초'], [6, '모란']]
[[4, '흑싸리'], [5, '초'], [6, '모란'], [2, '메조'], [3, '벚꽃'], [1, '송학']]
[[1, '송학'], [6, '모란'], [5, '초'], [2, '메조'], [3, '벚꽃'], [4, '흑싸리']]
[[3, '벚꽃'], [4, '흑싸리'], [2, '메조'], [5, '초'], [1, '송학'], [6, '모란']]
[[1, '송학'], [3, '벚꽃']]


In [ ]:
# 직접 모듈 함수 만들어서 사용하는것에서,
# __name__ 은 시작되는 함수에서는 __main__ 이되지만
# 불러온 다른모듈에서는 모듈이름이 저장된다. 
# 334 page 참고 

#모듈을 새로생성해서 새로운 함수를 만들수있고 그 모듈의 이름은 파일이름이되고,
#모듈의 함수를 import 해서 사용할수있다.
#다른곳에서 불러와서 사용할경우에는 __name__ 이  __main__이 되지 않는다는것을 생각해야한다.

# 9-3과 9-4 참고

#모듈이 담겨져있는 폴더를 패키지라고 한다.
#패키지명.모듈 로 접근할수있다.
#저장은 직접 python -- site-package 폴더에 저장하는방법과 ,
#import sys => sys.path.append('root폴더의 경로') 지정으로 저장하는방법이있다


# ex ) import package.module 로 접근할수있으며 
# ex ) pakage.module.function() 으로 사용할수있다.
# 폴더가 다중일경우에는 from package1.package2 import module as m 
# m.function() 으로 사용할수있다.

In [6]:
'''import turtle as t
t.fd(100) #100px직진 
t.seth(90) #절대각도 90도 위를 봄 
t.fd(100) # 위로 100px직진
t.setposition(100,-100) #좌표 x100y-100으로 이동 '''

#fd --> 직진
#right,left(각도) 는 현재 거북이의 진행방향에서 시계방향으로 고개를 돌리게함
#setheading() 은 절대각도로 반시계방향의 각도로 고개를 돌림 seth() 로 간략하게 가능
#goto(x,y) , setpos(x,y) , setposition(x,y) 로 좌표이동이가능함 물론 그림을그림
#거북이가 나타난 처음 중앙지점이 0,0좌표

#9-5코딩 (거북이로 삼각형과 사각형그리기)
#home() 은 거북이를 (0,0)으로 다시 되돌린다.
#pencolor('color')로 거북이 펜의 색상을 변경할수있다.


import turtle as t

t.shape('turtle') #거북이소환

#삼각형그리기
t.fd(100)
t.left(120)
t.fd(100)
t.left(120)
t.fd(100)
t.left(120)

#사각형 그리기
t.pencolor('blue')
for _ in range(4):
    t.left(90)
    t.fd(150)

#삼각형 그리기
t.pencolor('orange')
t.goto(100,-100)
t.goto(-100,-100)
t.home()



In [ ]:
import turtle as t

t.shape('turtle')  #거북이소환
t.setup (500,400) #윈도우 창의 크기를 지정
t.speed(1) #거북이의 속도를 조정한다 0~10 이 존재
# 1은 가장 느린속도 0이 가장최고속
t.home()
t.write('좌표 (0,0)') # 현재 자리에서 글씨를 남긴다.
#거북이 모양은 classic,turtle,square,arrow,cicle,triangle등이 있다.


In [ ]:
#9-6 코딩

import turtle as t

t.setup(500,400) # 초기 윈도의 크기 조정
t.speed(1) # 1에서 10까지의 거북이 속도 증가, 0이면 초고속
t.pu() # 이동에 선이 그려지지 않도록 설정 penup() , up() 과 같다.
t.goto(0,-100) # 이동

t.pd() # 이동에 선이 그려지도록 설정 pendown(),down()과 같다
t.hideturtle() # 거북이는 보이지 않도록 설정
t.fillcolor('red') # 내부 칠할 색을 설정한다.
t.begin_fill() # 칠하기를 시작한다.
t.circle(100) #크기가 100인 원을 그린다.
t.end_fill() #칠하기를 종료한다.


In [ ]:
#9-7 코딩 및 다각형그리기

''' 다각형 그리는 함수 정의
   def drawpolygon(n,size)
   한변의 길이가 size인 n각형 그리기

   for i in ragne(n):
       t.forward(size) # 선그리기
       t.left(360/n) # 각도수정 '''

import turtle as t

#색상 리스트
cols = ['red','blue','green','purple','magenta','black',
        'gray','yellow','cyan','orange','aqua']

def drawpolygon(n,size):
    for i in range(n):
        t.pencolor(cols[i % len(cols)]) # 펜 색상을 지정 
        t.forward(size)
        t.left(360/n)

t.setup(500,400) # 초기 윈도우 크기 조정
t.speed(3) #거북이속도3

t.pu() # 이동에 선이 그려지지 않도록
t.goto(-50,-170) #처음 위치로 이동

t.pd() #다각형을 그리기위해 꼬리를 내리고
#한 변의 길이가 100인 다각형 그리기
for i in range(3,12):
    drawpolygon(i,100) # 함수호출 3각형부터 11각형까지 그린다.


In [ ]:

import numpy as np
'''
data = np.array([1,2,3,4,5]) # array로 1차원배열생성
data # 배열값 프린트 
print(data) # data 값 확인
print(data.shape) # data 의 배열구조 확인. (행,열)
'''

'''리스트 사용한 넘파이 사용 '''
'''
lst = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(lst)
print(mat.shape)
'''
#값(3,3) 확인
#그냥 mat으로 출력하면 2차원배열 array형태로 출력되고
#print(mat)으로 출력하면 2차원배열형태로 그대로 출려된다 ( 콤마 차이 )

#9-8 코딩

#numpy 의 배열은 같은원소의 위치끼리 곱,뺄,나누기,더하기를 수행할수있다.

import numpy as np

aryA = np.array([1,2,3,4,5])
aryB = np.array([6,7,8,9,10])

print(aryA + aryB)
print(aryA - aryB)
print(aryA * aryB)
print(aryA / aryB)
print(np.matmul(aryA,aryB)) # 두행렬의 곱연산의 합을 뽑아냄 numpy.matmul(A,B)
print(aryA.dot(aryB)) # A.dot(B) 로 두행렬의 곱연산의 합을 뽑아낼수있음 A.dot(B)



In [42]:
# 9-9 코딩 2차원행렬의 사칙연산과 함수 matmul()

import  numpy  as np

data1 = [[1,2,3,4,5],[6,7,8,9,10]]
data2 = [[1,2,3,4,5],[1,2,3,4,5]]
a = np.array(data1)
b = np.array(data2)

print('각각의 2차원 행렬 출력: ')
print(a); print(b);
print()
print('행렬 합 출력: ')
print(a+b)
print('행렬 차 출력: ')
print(a-b)
print('행렬 곱 출력: ')
print(a*b)
print('행렬 나누기 출력: ')
print(a/b)

print()
print('각각의 2차원 행렬 출력: ')
data1 = [[1,2,3],[3,2,1]]
data2 = [[1,2],[3,4],[5,6]]
a = np.array(data1)
b = np.array(data2)
print(a); print(b)



ma = np.array(data1)
mb = np.array(data2)

print('ma.dot(b) 행렬 출력: ')
data2 = [[1,2,3,4,5],[1,2,3,4,5]]

print(ma.dot(mb)) # 수학의 행렬 곱 수행
print('numpy.matmul(a,b) 행렬 출력: ')
print(np.matmul(ma,mb)) #수학의 행렬 곱 수행


각각의 2차원 행렬 출력: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3 4 5]
 [1 2 3 4 5]]

행렬 합 출력: 
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]
행렬 차 출력: 
[[0 0 0 0 0]
 [5 5 5 5 5]]
행렬 곱 출력: 
[[ 1  4  9 16 25]
 [ 6 14 24 36 50]]
행렬 나누기 출력: 
[[1.         1.         1.         1.         1.        ]
 [6.         3.5        2.66666667 2.25       2.        ]]

각각의 2차원 행렬 출력: 
[[1 2 3]
 [3 2 1]]
[[1 2]
 [3 4]
 [5 6]]
ma.dot(b) 행렬 출력: 
[[22 28]
 [14 20]]
numpy.matmul(a,b) 행렬 출력: 
[[22 28]
 [14 20]]


In [ ]:
# matplotlib 데이터 시각화를위한 서드파티 모듈 
# pip install matplotlib  < 파워쉘에서 실행 설치 
# 다양한 차트와 플롯스타일을 지정할수있음.
#9-10코딩

from matplotlib import pyplot as plt 

plt.plot([2,4,6,8],[8,10,3,6]) #plot() -> 라인플롯 그리는 함수 #가로축 ,  세로축 값 대칭 라인플롯생성
plt.show() #-> show() 로 항상 보여줘야함 


In [ ]:
#9-11 코딩
#barh() 함수로 가로 막대그래프를 그릴수있다.
# 함수 title() 로 제목을 , xlabel() 로 가로축 , ylabel() 로 세로축을 지정할수있음.

import matplotlib.pyplot as plt

objects = ('Python','Java','C++','C#','C','Kotlin')ㅏ
performance = [10,8,6,4,7,2]

plt.title('Programming language usage') # 제목 설정 
plt.xlabel('Usage') # x축 레이블 타이틀지정
plt.ylabe('Programming language') # y축 레이블 타이틀지정

plt.barh(objects,performance,height=0.5,color='red') # barh 가로막대그래프생성 
plt.show()
#barh (항목,그래프수치값,막대그래프두께,그래프색상) 을 매개변수로 지정할수있음
#plt.show()는 필수로 지정해야함 안지정하면 그래프가 보이지 않음
#height 는 1에 가까울수록  여백이 줄어든다.(1이 최대치)

 

In [40]:
import  numpy as np
data = [[1,2,3],[4,5,6]]
data1 = [[2,3],[4,5],[5,6]]

print(data); print(data1)

 

[[1, 2, 3], [4, 5, 6]]
[[2, 3], [4, 5], [5, 6]]
